language: python
python:
  - '3.5'
  - '3.6'
  - 3.7-dev
  - nightly
install:
  - pip install .
  - pip install -r test_requirements.txt
script:
  - nosetests
deploy:
  provider: pypi
  user: PYPI_USERNAME
  password: PYPI_PASSWORD
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    branch: master
    tags: true
env:
  global:
    - secure: McpuYlMmjtyA49EMdOsmbGgiM4hg2HgdYSzTIjtD0OvQstwTliDfZjizfmJNrFYNiZ15DEsBFj6VrO1+w299cdjA+XTHI/1jtJXC5k+5UyehGLi32TCmC3Q5gihK3Vdil2GFDjQiJgzg/IMVWDnNk48botNjTIBsTubZiQAf2e1VpQWRfQ4U71tmuzMss3tRNZvhXtoVA9UJzsNosFG//5Lt6r5fQxJ0LOdv+7owMGtXXifK6WtK83n8qUQ2a9zBEvwH4OoqohQOAX6IgRvitXfLGYqWlMiorIzku7na1Qfc9bhku5l9/f5n3FpfMJnWkKNbSPi6/q0y7IYLzB5aMDJt0CEYFCkrW0iXcFNZCGKCvRSMT+tXwIwZx4UTkm1Os4ZJpJzt3gh8rD8wM4gnw8dA+yB7i81iycLDU+7YLkQBiPP8rACig7Jk/3bfYUoFLTh7Pj2HEEoNHIkYBh1ImSgZG/BebA79OPF5128ZUzh1zdnXejFj74WCb2bJ6uuWbh1aFkGY6q377tWTxFgS6yja57pINU6DqSdFrH7PAP4YVgrbjNKDa8ypIb0rOdHyaSExjn+tRe8ZwDTIjtX1zPTR5mTjx+erO+5VY+zwxz+XXPKnpXkxXz4M/QFSvDLO/GODHVILM+xBq852pYqi5s4Ljd8fxmSG3L9aGuULi14=
    - secure: voK7GvszMg8PqpGOqazddYwnT0FheSpu5PhOhnGmb2zM1YJcob9xcd+1BAR0KJbByqbkeEwNQrToStbWeLA8it7pBpxVEDO5gFN870qa8u5DnO2XS3uv5ylhJ7WNT53btsRM1d/6S+9G+jns4gPFe78AMQ3PieIeQz2pw9QE8WRETlar8KfoPbSW4DMsDjL4XA9sYcJZRAo9RSSPU5Hm1eLOCcTxJNY4veKt32T4ltoI9+eiQlNeuEFgIbyFmWQ0NvqtZRZ7hqBZLIJY22K6H7UOqUsCTGpaCS9RW01wp7PJ/cp/HtJz3hzy+zkDhaD+FQCOaoI8ixOMb0Da92/rL5ezkw/hooQeYFZ9IZ/LHJQQo4FxW3QdSfdXk84wgClcCAxewdfp/eCCCPA/cC2eTuYoF94HtXa6Hd0JX/vjBbuK9K7p3GOOu4flhi9lGAGs4xpm8/RJDwwXK3I1nWJNYtFRkicJ7G2nRCuv75+4xUAqQi0A78Ud50XJUaM6t3lsbf+KDMSITbyrv/4oFV2feF26YDoxi1C46Gn8ajAItDxwU+2qtHNR531fIFl6pFzJ0YJuJbp3/qpJ5C5Gy1mUn2pQAzoseOr1l07F/4j5y5IZzke9zXm81iSk3ZYu6AbZlFroXC+gaW1D6wM11pagehPAXBcDnSK17mNf6yxziVo=
